post:
  tags:
    - 강아지
  summary: 강아지 등록
  description: 새로운 강아지 정보를 등록한다.
  parameters:
    - in: cookie
      name: Authorization
      required: true
      schema:
        type: string
        example: "Bearer ${accessToken}"
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            name:
              type: string
              description: 강아지 이름
              example: 덕지
            breed:
              type: string
              description: 견종
              example: 시츄
            gender:
              type: string
              description: 강아지 성별
              enum:
                - MALE
                - FEMALE
            isNeutered:
              type: boolean
              description: 중성화 여부
            birth:
              type: string
              description: 강아지 생일
              nullable: true
              example: YYYY-MM-DD
            weight:
              type: number
              description: 강아지 몸무게
              example: 10
            profilePhotoUrl:
              type: string
              description: 강아지 사진 URL
              example: https://path/to/profile-photo
          required:
            - name
            - breed
            - gender
            - isNeutered
            - birth
            - weight
            - profilePhotoUrl
  responses:
    "201":
      description: 강아지가 정상적으로 등록된 경우
      content:
        text/plain:
          schema:
            type: boolean
            example: true
    "401":
      description: Authorization header가 없거나 유효한 access token이 아닌 경우
    "404":
      description: 회원을 찾을 수 없는 경우

get:
  tags:
    - 강아지
  summary: 강아지 목록
  description: .
  parameters:
    - in: cookie
      name: "Authorization"
      type: string
      example: "Bearer ${accessToken}"
  responses:
    "200":
      description: 유저가 소유한 강아지 목록 반환, 없으면 빈배열 반환
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: number
                  description: 강아지 id
                name:
                  type: string
                  description: 강아지 이름
                  example: 덕지
                breed:
                  type: string
                  description: 강아지 종
                  example: 시츄
                gender:
                  type: string
                  description: 강아지 성별
                  enum:
                    - MALE
                    - FEMALE
                birth:
                  type: string
                  description: 강아지 생일
                  example: YYYY-MM-DD
                weight:
                  type: number
                  description: 강아지 몸무게
                  example: 10
                profilePhotoUrl:
                  type: string
                  description: 강아지 사진 URL
                  example: https://path/to/profile-photo
    "401":
      description: Authorization header가 없거나 유효한 access token이 아닌 경우
