x-logging: &default-logging
  options:
    max-size: '10m'
    max-file: '3'

x-backend-common: &backend-common
  logging: *default-logging
  platform: linux/amd64
  networks:
    - default

x-mysql-image: &mysql-image
  image: mysql:8.0.22
  platform: linux/amd64

x-redis-image: &redis-image
  image: redis:7.0.15
  platform: linux/amd64

services:
  db:
    <<: *mysql-image
    container_name: dangdang-mysql
    profiles: ['server']
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    env_file: ./backend/server/.env.local
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/mysql/data:/var/lib/mysql --user 1000
      - ./db/mysql/config:/etc/mysql/conf.d --user 1000
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=root"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  server:
    <<: *backend-common
    container_name: dangdang-server
    profiles: ['server']
    image: dangdang-server
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: ./server/Dockerfile
    env_file: ./backend/server/.env.local
    volumes:
      - ./backend/server:/app
      - /app/node_modules
    environment:
      - MYSQL_HOST=db
    ports:
      - 3333:3333
    networks:
      - default
    depends_on:
      - db
    working_dir: /app/server
    command: npm run start

  redis:
    <<: *redis-image
    container_name: dangdang-weather-redis
    profiles: ['weather']
    ports:
      - 6379:6379
    networks:
      - default
    command: redis-server
    volumes:
      - ./backend/weather-api-module/redis-backup:/data

  weather:
    <<: *backend-common
    container_name: dangdang-weather-api-module
    profiles: ['weather']
    image: dangdang-weather-api-module
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: ./weather-api-module/Dockerfile
    env_file: ./backend/weather-api-module/.env.local
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - REDIS_HOST=redis
    ports:
      - 3335:3335
    depends_on:
      - redis
    working_dir: /app/weather-api-module
    command: npm run start

networks:
  default:
    driver: bridge
volumes:
  db:
    driver: local

