#!/bin/sh

NC='\033[0m'
GREEN='\033[0;32m'
RED='\033[0;31m'

check_and_start_mysql_container() {
    if [ "$(docker ps -aq -f name=local-mysql)" ]; then
		if [ "$(docker ps -q -f name=local-mysql)" ]; then
            echo -e "${GREEN}[INFO]${NC} 'local-mysql' container가 실행 중입니다."
		else
            echo -e "${GREEN}[INFO]${NC} 'local-mysql' container를 시작합니다..."
            docker start local-mysql
		fi
	else
		if [ -f .env.test ]; then
            export $(cat .env.test | xargs)
        else
            echo -e "${RED}[ERROR]${NC} '.env.test' 파일이 존재하지 않습니다."
            exit 1
		fi

		echo -e "${GREEN}[INFO]${NC} 'local-mysql' container를 생성하고 시작합니다..."
		docker run -d --name local-mysql --platform linux/amd64 -p $MYSQL_PORT:3306 \
		-e MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD -e MYSQL_DATABASE=$MYSQL_DATABASE mysql:8.4.0 \
		--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
	fi
}

# Check if docker is running
if ! docker info > /dev/null 2>&1; then
    echo -e "${RED}[ERROR]${NC} Docker deamon이 실행 중이 아닙니다. Docker를 실행하고 다시 시도해주세요."
    exit 1
fi

cd backend

check_and_start_mysql_container

# Run unit tests
echo -e "${GREEN}[INFO]${NC} Unit test 시작..."
if ! npm run test; then
	echo -e "${RED}[ERROR]${NC} Unit test를 통과하지 못했습니다."
	exit 1
fi

# Run e2e tests
echo -e "${GREEN}[INFO]${NC} E2E test 시작..."
if ! npm run test:e2e; then
	echo -e "${RED}[ERROR]${NC} E2E test를 통과하지 못했습니다."
	exit 1
fi

echo -e "${GREEN}[INFO]${NC} 모든 test를 통과했습니다."